/* BeforeWise full-library visual + mobile consistency layer */
(function(){
  const ART_BY_CATEGORY={'Travel':'art-travel.jpg','Work':'art-work.jpg','Home & Life':'art-home.jpg','Buying & Money':'art-buying.jpg','Digital':'art-digital.jpg','Saudi & GCC':'art-saudi.jpg','Events & Social':'art-events.jpg','Family':'art-family.jpg'};
  function artFileFor(s){if(s.id==='used-car')return 'car-editorial.jpg';if(String(s.id||'').startsWith('custom-'))return 'art-custom.jpg';return ART_BY_CATEGORY[s.category]||'art-custom.jpg'}
  function artClassFor(s){if(s.id==='used-car')return 'used-car';return (s.category||'custom').toLowerCase().replace(/&/g,'and').replace(/[^a-z0-9]+/g,'-').replace(/^-|-$/g,'')}
  function scenarioVisualAll(s){const file=artFileFor(s),cls=artClassFor(s);const label=s.id==='used-car'?'Vehicle field note':`${s.category||'Personal'} field note`;return `<div class="scenario-visual art-${cls}" role="img" aria-label="Editorial illustration for ${esc(s.title)}" style="--scenario-art:url('${file}')"><span>${esc(label)}</span></div>`}
  checklistItem=function(s,item,index){const checked=!!store.checked[itemKey(s,index)];const isDont=item.type==='dont';return `<label class="field-check ${checked?'checked':''} ${isDont?'is-dont':''}" data-type="${item.type}"><input class="checkbox" type="checkbox" data-check="${index}" ${checked?'checked':''} /><span class="check-copy"><span class="mobile-type ${item.type}">${typeLabel(item.type)}</span><strong>${esc(item.text)}</strong>${item.type==='dont'?'<small>Avoid this if you can.</small>':''}</span><span class="check-type ${item.type}">${typeLabel(item.type)}</span></label>`};
  scenarioView=function(s){const saved=store.saved.includes(s.id),prog=progressFor(s);const visibleIndices=s.items.map((_,i)=>i).filter(i=>state.filter==='all'||s.items[i].type===state.filter);const stages=[...new Set(s.items.map(i=>i.stage))];const fieldGuideLabel=s.id==='used-car'?`${s.items.length} things worth knowing before you pay.`:`${s.items.length} things worth knowing before you ${s.title.toLowerCase().startsWith('going')?'go':'begin'}.`;return `<div class="scenario-layout"><div class="scenario-main"><div class="scenario-topline"><button id="backBtn" class="back-link">Back to situations</button><button id="saveScenario" class="save-link ${saved?'saved':''}">${saved?'Saved':'Save'}</button></div><header class="scenario-hero"><div class="scenario-title-wrap"><span class="hero-kicker">${esc(s.category)} field guide</span><h1>${esc(s.title)}</h1><p>${esc(fieldGuideLabel)}</p></div>${scenarioVisualAll(s)}</header>${filterPills(s)}<div class="mobile-progress-strip"><span>${prog.done}/${prog.total}</span><div><strong>${prog.pct}% prepared</strong><small>Progress is saved locally.</small></div></div><div class="stage-stack">${stages.map((stage,i)=>stageBlock(s,stage,i,visibleIndices)).join('')}</div>${s.sources?.length?`<section class="mobile-sources"><span class="source-kicker">Trusted references</span><h3>Sources used for this guide</h3>${s.sources.map(src=>`<a href="${src.url}" target="_blank" rel="noreferrer"><strong>${esc(src.org)}</strong><small>${esc(src.title)}</small><em>Open</em></a>`).join('')}</section>`:''}</div><aside class="scenario-aside"><section class="side-card progress-card"><span>Your progress</span><div class="progress-ring" style="--progress:${prog.pct}"><strong>${prog.done}<small>/${prog.total}</small></strong></div><p>${prog.pct===100?'You’re BeforeWise.':prog.done===0?'Ready to start.':'Good progress.'}</p></section>${stageRail(s)}${sourceCard(s)}<button id="saveScenarioAside" class="save-card ${saved?'saved':''}"><strong>${saved?'Saved checklist':'Save this checklist'}</strong><span>${saved?'Available in your saved field guides.':'Add this guide to your saved items.'}</span></button></aside></div><div class="mobile-progress-footer"><div class="footer-progress"><strong>${prog.done}/${prog.total}</strong></div><div><strong>${prog.pct===100?'You’re BeforeWise.':prog.done===0?'Ready when you are.':'Good progress!'}</strong><small>${prog.pct===100?'Everything on this guide is checked.':'Keep going — the important things are visible.'}</small></div><button id="mobileSave">${saved?'Saved':'Save'}</button></div>`};
  const bindBeforeAllFix=bind;
  bind=function(){bindBeforeAllFix();document.querySelectorAll('[data-filter]').forEach(b=>b.onclick=()=>{state.filter=b.dataset.filter;const s=scenarioById(state.scenarioId);if(s&&state.filter!=='all'){const hit=s.items.find(i=>i.type===state.filter);if(hit)state.expandedStage=hit.stage}render()})};
  render();
})();